// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcxemzvjlacdzmymmcrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjeGVtenZqbGFjZHpteW1tY3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NTI5MTcsImV4cCI6MjA1MTEyODkxN30.AYGUvikuGp-oNu1AwoR6bGgywUUrsMe0J8BWW5UFbbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);